version: '3'

services:
# Pasos para levantar el sistema: 

# 1) Levantar etcd
# docker run -p 2379:2379 quay.io/coreos/etcd:v3.2.0 \
#   /usr/local/bin/etcd \
#   --advertise-client-urls http://0.0.0.0:2379 \
#   --listen-client-urls http://0.0.0.0:2379 \
#   --initial-advertise-peer-urls http://0.0.0.0:2380 \
#   --listen-peer-urls http://0.0.0.0:2380 \
#   --initial-cluster "default=http://0.0.0.0:2380"

# 2) Levantar la base de datos mysql
# para correr solo la base de datos:
# docker-compose run --service-ports database


# 3) ir a cada servicio y levantar con sbt "run {port}" siendo {port} el puerto donde en el cual va a correr.

  database:
    image: mysql:8.0.15
    environment:
      MYSQL_ROOT_PASSWORD: "pass"
      MYSQL_DATABASE: "db-sist"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "pass"
    ports:
      - "3306:3306"





     

  
 

 

