version: '3'

services:
# para levantar etcd

# docker run -p 2379:2379 quay.io/coreos/etcd:v3.2.0 \
#   /usr/local/bin/etcd \
#   --advertise-client-urls http://0.0.0.0:2379 \
#   --listen-client-urls http://0.0.0.0:2379 \
#   --initial-advertise-peer-urls http://0.0.0.0:2380 \
#   --listen-peer-urls http://0.0.0.0:2380 \
#   --initial-cluster "default=http://0.0.0.0:2380"


# para correr solo la base de datos:
# docker-compose run --service-ports database
# cambiar url de jdbc en app.conf de 'host.docker.internal' a 'localhost' 
  database:
    image: mysql:8.0.15
    environment:
      MYSQL_ROOT_PASSWORD: "pass"
      MYSQL_DATABASE: "db-sist"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "pass"
    ports:
      - "3306:3306"


# para levantar base de datos y servicios
# docker-compose down
# docker-compose up --force-recreate


  product-service:
    build: ./product-service-grpc
    depends_on:
    - database
    ports:
      - "9000:9000"

  product-service-2:
    build: ./product-service-grpc
    depends_on:
    - database
    ports:
      - "9001:9000"


  user-service:
    build: ./user-service-grpc
    depends_on:
    - database
    ports:
      - "8000:8000"

  user-service-2:
    build: ./user-service-grpc
    depends_on:
    - database
    ports:
      - "8001:8000"




     

  
 

 

