apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: notification-deployment
spec:
  selector:
    matchLabels:
      app: notification-app
  replicas: 1
  template:
    metadata:
      labels:
        app: notification-app
    spec:
      containers:
        - name: notification
          image: notification/latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: notification-app
  name: notification-svc
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - port: 9000
  selector:
    app: notification-app
