apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: product-deployment
spec:
  selector:
    matchLabels:
      app: product-app
  replicas: 1
  template:
    metadata:
      labels:
        app: product-app
    spec:
      containers:
        - name: product
          image: products/latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000
          env:
          - name: DB-URL
            valueFrom:
              configMapKeyRef:
                 name: my-config
                 key: dbUrl

---
# apiVersion: v1
# kind: Service
# metadata:
#  labels:
#    app: product-app
#  name: product-svc
#  namespace: default
# spec:
#  type: LoadBalancer
#  ports:
#    - port: 9000
#  selector:
#    app: product-app

apiVersion: v1
kind: Service
metadata:
  labels:
    app: product-app
  name: product-svc
spec:
  selector:
    app: product-app
  ports:
    - port: 9000
