apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: wishlist-deployment
spec:
  selector:
    matchLabels:
      app: wishlist-app
  replicas: 1
  template:
    metadata:
      labels:
        app: wishlist-app
    spec:
      containers:
        - name: wishlist
          image: wishlist/latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000
---
#apiVersion: v1
#kind: Service
#metadata:
#  labels:
#    app: wishlist-app
#  name: wishlist-svc
#  namespace: default
#spec:
#  type: LoadBalancer
#  ports:
#    - port: 9000
#  selector:
#    app: wishlist-app

apiVersion: v1
kind: Service
metadata:
  labels:
    app: wishlist-app
  name: wishlist-svc
spec:
  selector:
    app: wishlist-app
  ports:
    - port: 9000